import {CLUBS,DT,generateCourse,makeBall,strike,step,dist,clamp,terrain,preview} from './engine.js';
import {Renderer} from './render.js';
const $=id=>document.getElementById(id);
const canvas=$('course'),renderer=new Renderer(canvas),modal=$('modal');
const STORAGE='golfi-round-v1';
const freshSeed=()=>Array.from(crypto.getRandomValues(new Uint8Array(4)),x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();
let saved;try{saved=JSON.parse(localStorage.getItem(STORAGE));}catch{}
const urlSeed=new URL(location.href).searchParams.get('seed');
const seed=(urlSeed||saved?.seed||freshSeed()).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,24)||freshSeed();
const validSaved=saved&&saved.seed===seed&&Number.isInteger(saved.hole)&&saved.hole>=0&&saved.hole<9&&Array.isArray(saved.scores)&&saved.scores.length===saved.hole&&saved.scores.every(s=>Number.isInteger(s.strokes)&&s.strokes>=0&&s.strokes<=99)&&Number.isInteger(saved.strokes)&&saved.strokes>=0&&saved.strokes<=99&&saved.ball&&['x','y','z','vx','vy','vz','age'].every(k=>Number.isFinite(saved.ball[k]))&&saved.ball.shotFrom&&Number.isFinite(saved.ball.shotFrom.x)&&Number.isFinite(saved.ball.shotFrom.y);
const state={seed,hole:validSaved?saved.hole:0,scores:validSaved?saved.scores:[],strokes:validSaved?saved.strokes:0,club:'driver',angle:-Math.PI/2,power:0,phase:'ready',swingProgress:0,particles:[],aim:null};
let course,charge=null,drag=null,pendingShot=null,swingTime=0,toastTimer,accumulator=0,lastTime=0,previewAt=0,audio=null,sound=false;
try{sound=localStorage.getItem('golfi-sound')==='on';}catch{}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({seed:state.seed,hole:state.hole,scores:state.scores,strokes:state.strokes,ball:state.ball}));}catch{}}
function scoreText(n){return n===0?'E':n>0?'+'+n:String(n);}
function totalScore(){return state.scores.reduce((n,s)=>n+s.strokes-s.par,0);}
function setClub(club,force=false){if(!force&&(state.phase!=='ready'||state.ball?.moving))return;state.club=club;document.querySelectorAll('[data-club]').forEach(el=>{const active=el.dataset.club===club;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});$('club-detail').textContent=CLUBS[club].label;state.aim=null;}
function loadHole(restore){course=generateCourse(state.seed,state.hole);state.ball=restore||makeBall(course.tee);state.phase=state.ball.sunk?'holed':'ready';state.power=0;state.aim=null;state.particles=[];renderer.build(course);state.angle=Math.atan2(course.pin.y-state.ball.y,course.pin.x-state.ball.x);const d=dist(state.ball,course.pin);setClub(d<75?'putter':d<155?'wedge':d<300?'iron':'driver',true);$('course-name').textContent=course.name.toUpperCase();$('seed-label').textContent='FIELD NOTES / '+state.seed;$('hole-number').textContent=String(state.hole+1).padStart(2,'0');$('par').textContent=course.par;$('wind').textContent=course.wind.speed.toFixed(1);$('wind-arrow').textContent='↑';$('wind-arrow').style.transform=`rotate(${Math.atan2(course.wind.y,course.wind.x)*180/Math.PI+90}deg)`;updateUI();save();}
function updateUI(){const b=state.ball;const lie=terrain(course,b);$('strokes').textContent=state.strokes;$('total').textContent=scoreText(totalScore());$('distance').textContent=Math.round(dist(b,course.pin)*.5);$('lie').textContent='● '+(b.z>1?'IN FLIGHT':lie==='tee'?'TEE BOX':lie.toUpperCase());$('swing').disabled=b.moving||state.phase!=='ready';document.querySelectorAll('[data-club]').forEach(el=>el.disabled=b.moving||state.phase!=='ready');$('power-value').textContent=Math.round(state.power*100)+'%';$('power-fill').style.width=state.power*100+'%';$('hint').textContent=b.moving?'A little patience. Let it roll.':state.phase==='holed'?'Beautiful. On to the next.':'Drag back on the course & release to shoot';}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400);}
function tone(freq,duration=.12,type='sine',gain=.045){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const oscillator=audio.createOscillator(),volume=audio.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(freq,audio.currentTime);volume.gain.setValueAtTime(gain,audio.currentTime);volume.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);oscillator.connect(volume);volume.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+duration);}catch{}}
function unlockAudio(){if(sound){tone(1,.01,'sine',.001);}}
function fire(){if(state.phase!=='ready'||state.ball.moving||state.power<.025){cancelInput();return;}pendingShot={angle:state.angle,power:state.power,club:state.club};state.phase='swing';swingTime=0;state.swingProgress=0;state.aim=null;charge=null;drag=null;$('cancel').hidden=true;renderer.trail=[];updateUI();}
function cancelInput(){charge=null;drag=null;state.power=0;state.aim=null;$('cancel').hidden=true;updateUI();}
function canAim(){return state.phase==='ready'&&!state.ball.moving&&!modal.open;}
function eventPoint(e){const rect=canvas.getBoundingClientRect();return {x:e.clientX-rect.left,y:e.clientY-rect.top};}
canvas.addEventListener('pointerdown',e=>{if(!canAim()||drag||charge||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();unlockAudio();canvas.setPointerCapture(e.pointerId);const p=eventPoint(e);drag={id:e.pointerId,start:p,current:p};});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=eventPoint(e);drag.current=p;const dx=drag.start.x-p.x,dy=drag.start.y-p.y,d=Math.hypot(dx,dy);if(d>7){state.angle=Math.atan2(dy,dx);state.power=clamp((d-7)/Math.min(145,renderer.h*.38),0,1);$('cancel').hidden=false;updateUI();}});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const p=eventPoint(e),d=Math.hypot(p.x-drag.start.x,p.y-drag.start.y);if(d<8){const world=renderer.toWorld(p.x,p.y);state.angle=Math.atan2(world.y-state.ball.y,world.x-state.ball.x);cancelInput();toast('Aim set · hold the swing button');}else fire();drag=null;});
canvas.addEventListener('pointercancel',cancelInput);
canvas.addEventListener('lostpointercapture',()=>{if(drag)cancelInput();});
$('swing').addEventListener('pointerdown',e=>{if(!canAim()||charge||drag||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();unlockAudio();$('swing').setPointerCapture(e.pointerId);charge={id:e.pointerId,start:performance.now()};state.power=.03;$('cancel').hidden=false;});
$('swing').addEventListener('pointerup',e=>{if(charge?.id===e.pointerId)fire();});
$('swing').addEventListener('pointercancel',cancelInput);
$('swing').addEventListener('lostpointercapture',()=>{if(charge)cancelInput();});
$('cancel').addEventListener('click',cancelInput);
window.addEventListener('keydown',e=>{if(modal.open)return;if(e.code==='Escape'){cancelInput();return;}if(!canAim())return;if(['ArrowLeft','ArrowRight','Space'].includes(e.code)){e.preventDefault();if(e.code==='ArrowLeft')state.angle-=.035;if(e.code==='ArrowRight')state.angle+=.035;if(e.code==='Space'&&!charge&&!drag&&!e.repeat){unlockAudio();charge={id:'keyboard',start:performance.now()};}}if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))setClub(Object.keys(CLUBS)[Number(e.code.slice(-1))-1]);});
window.addEventListener('keyup',e=>{if(e.code==='Space'&&charge?.id==='keyboard'){e.preventDefault();fire();}});
window.addEventListener('blur',()=>{if(state.phase==='ready')cancelInput();});
document.addEventListener('visibilitychange',()=>{lastTime=0;accumulator=0;if(document.hidden){if(state.phase==='ready')cancelInput();save();}});
document.querySelectorAll('[data-club]').forEach(button=>button.addEventListener('click',()=>{cancelInput();setClub(button.dataset.club);}));
function openModal(html){cancelInput();$('modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
$('close-modal').addEventListener('click',()=>modal.close());
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
function help(){openModal(`<span class="eyebrow">WELCOME TO YOUR SMALL ESCAPE</span><h1>Less rush.<br>More fairway.</h1><div class="instruction"><b>01</b><p><strong>Pull back. Let go.</strong>Drag anywhere on the course, opposite the direction you want to hit. A longer pull means more power.</p></div><div class="instruction"><b>02</b><p><strong>Or take it one step at a time.</strong>Tap the course to aim. Hold the swing button to build power, then release. Power peaks, then falls.</p></div><div class="instruction"><b>03</b><p><strong>Find your touch.</strong>Driver for distance, iron for control, wedge to clear trouble, putter on the green. Sand and rough slow you down. Water costs one penalty stroke and a replay.</p></div><p>The dotted line previews your shot. Wind affects flight; faint contours mark gentle green slopes. Nine holes, a new course every round.</p><p>Keyboard: ← / → aim · hold Space to swing · 1–4 select club. Progress saves automatically.</p><button class="primary" id="lets-play">Let’s play ↗</button>`);$('lets-play').onclick=()=>{try{localStorage.setItem('golfi-help','seen');}catch{}modal.close();};}
$('help').onclick=help;
function scoreRows(includeCurrent=true){return Array.from({length:9},(_,i)=>{const s=state.scores[i],p=generateCourse(state.seed,i).par;return `<tr><td>${String(i+1).padStart(2,'0')}${i===state.hole?' •':''}</td><td>${p}</td><td>${s?s.strokes:includeCurrent&&i===state.hole?state.strokes:'—'}</td><td>${s?scoreText(s.strokes-p):'—'}</td></tr>`;}).join('');}
function shareSeed(){const url=new URL(location.href);url.search='';url.searchParams.set('seed',state.seed);if(navigator.clipboard?.writeText)navigator.clipboard.writeText(url.href).then(()=>toast('Course link copied')).catch(()=>showLink(url.href));else showLink(url.href);}
function showLink(url){openModal('<span class="eyebrow">SAME COURSE. FRIENDLY RIVALRY.</span><h1>Share the green.</h1><p>Copy this link to replay the same nine holes.</p><input id="share-link" readonly style="width:100%;padding:12px;border:1px solid #ccd5c8;border-radius:8px">');$('share-link').value=url;$('share-link').select();}
function showScorecard(){openModal(`<span class="eyebrow">FIELD NOTES / ${state.seed}</span><h1>Your round.</h1><div class="big-score">${scoreText(totalScore())}</div><p>${state.scores.length} of 9 holes complete</p><table><thead><tr><th>HOLE</th><th>PAR</th><th>SHOTS</th><th>+/−</th></tr></thead><tbody>${scoreRows()}</tbody></table><button class="primary" id="resume">${state.ball.sunk?'Continue ↗':'Back to the fairway ↗'}</button><button class="secondary" id="share">Copy course link</button>`);$('resume').onclick=()=>{modal.close();if(state.ball.sunk)finishHole();};$('share').onclick=shareSeed;}
$('scorecard').onclick=showScorecard;
function newRound(seed){cancelInput();state.seed=seed;state.hole=0;state.scores=[];state.strokes=0;const url=new URL(location.href);url.searchParams.set('seed',seed);history.replaceState(null,'',url);loadHole();modal.close();toast('Fresh air. Fresh fairways.');}
$('new-round').onclick=()=>{openModal('<span class="eyebrow">ANOTHER LITTLE ESCAPE</span><h1>Fresh fairways?</h1><p>Start a new 9-hole course. Your current round will be replaced.</p><button class="primary" id="confirm-new">Generate new course ↻</button><button class="secondary" id="keep-playing">Keep playing</button>');$('confirm-new').onclick=()=>newRound(freshSeed());$('keep-playing').onclick=()=>modal.close();};
function finishHole(){const shots=state.strokes,delta=shots-course.par;const label=shots===1?'Hole in one!':delta<=-3?'Albatross!':delta===-2?'Eagle!':delta===-1?'Birdie. Lovely.':delta===0?'Right on par.':delta===1?'A little bogey.':'In the cup.';const final=state.hole===8;
  openModal(`<span class="eyebrow">${final?'NINE HOLES. ONE GOOD ESCAPE.':'HOLE '+String(state.hole+1).padStart(2,'0')+' COMPLETE'}</span><h1>${final?'That’s a round.':label}</h1><div class="big-score">${final?scoreText(totalScore()):shots}</div><p>${final?'Your final score against par. Come back for another small escape.':`strokes · par ${course.par} · ${scoreText(delta)}<br>Round so far: ${scoreText(totalScore())}`}</p><button class="primary" id="next">${final?'A new round ↻':'Next fairway ↗'}</button><button class="secondary" id="view-score">View scorecard</button><button class="secondary" id="share">Copy course link</button>`);
  $('next').onclick=()=>{if(final)newRound(freshSeed());else{state.hole++;state.strokes=0;modal.close();loadHole();}};$('view-score').onclick=showScorecard;$('share').onclick=shareSeed;
}
function onHole(){state.phase='holed';state.scores[state.hole]={strokes:state.strokes,par:course.par};for(let i=0;i<35;i++)state.particles.push({x:course.pin.x,y:course.pin.y,vx:(Math.random()-.5)*120,vy:-25-Math.random()*100,life:1,color:['#f7f2d4','#e5a874','#315e46'][i%3]});tone(523,.2);setTimeout(()=>tone(659,.2),100);setTimeout(()=>tone(784,.3),220);navigator.vibrate?.([20,40,20]);save();updateUI();const completedBall=state.ball;setTimeout(()=>{if(state.ball===completedBall&&state.ball.sunk)finishHole();},900);}
function syncSound(){$('sound-off').hidden=sound;$('sound').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('sound').setAttribute('aria-pressed',String(sound));}
$('sound').onclick=()=>{sound=!sound;try{localStorage.setItem('golfi-sound',sound?'on':'off');}catch{}syncSound();if(sound)tone(660);};syncSound();
new ResizeObserver(()=>{renderer.resize();}).observe($('course-wrap'));
function loop(now){const elapsed=lastTime?Math.min((now-lastTime)/1000,.1):0;lastTime=now;
  if(!modal.open){
    if(charge){const t=(now-charge.start)/1350;state.power=.03+.97*(1-Math.abs(1-(t%2)));}
    if(state.phase==='swing'){swingTime+=elapsed;state.swingProgress=clamp(swingTime/.22,0,1);if(swingTime>=.22){const p=pendingShot;if(strike(state.ball,course,p.club,p.angle,p.power)){state.strokes++;tone(150+150*p.power,.08,'triangle',.1);navigator.vibrate?.(12);}state.phase='ready';state.power=0;save();}}
    if(state.ball.moving){accumulator+=elapsed;while(accumulator>=DT&&state.ball.moving){const event=step(state.ball,course);accumulator-=DT;if(event==='hole')onHole();if(event==='water'){state.strokes++;toast('Water · +1 penalty · replay your shot');save();}if(event==='rest'||event==='water'){state.angle=Math.atan2(course.pin.y-state.ball.y,course.pin.x-state.ball.x);if(terrain(course,state.ball)==='green')setClub('putter');else if(terrain(course,state.ball)==='sand')setClub('wedge');save();}}}else accumulator=0;
    if(state.power>.02&&now-previewAt>70){state.aim=preview(course,state.ball,state.club,state.angle,state.power);previewAt=now;}
    for(const p of state.particles){p.x+=p.vx*elapsed;p.y+=p.vy*elapsed;p.vy+=140*elapsed;p.life-=elapsed*.7;}state.particles=state.particles.filter(p=>p.life>0);
  }
  updateUI();renderer.draw(state,now/1000);requestAnimationFrame(loop);
}
// A finished hole is recorded, so it has one more score than an in-progress hole.
if(saved&&saved.seed===seed&&saved.ball?.sunk&&Number.isInteger(saved.hole)&&saved.hole>=0&&saved.hole<9&&Array.isArray(saved.scores)&&saved.scores.length===saved.hole+1&&saved.scores.every(s=>Number.isInteger(s.strokes)&&s.strokes>0&&s.strokes<=99)){
  state.hole=saved.hole;state.scores=saved.scores;state.strokes=saved.scores[saved.hole].strokes;loadHole({...makeBall(generateCourse(seed,state.hole).pin),sunk:true});finishHole();
}else{loadHole(validSaved?saved.ball:null);let seen=false;try{seen=localStorage.getItem('golfi-help')==='seen';}catch{}if(!seen)help();}
requestAnimationFrame(loop);
