import test from 'node:test';
import assert from 'node:assert/strict';
import {generateCourse,makeBall,terrain,strike,step,preview,CLUBS,dist,pathDistance} from '../engine.js';
function flat(lie='green'){const c=generateCourse('flat');c.water=[];c.bunkers=[];c.trees=[];c.wind={x:0,y:0};c.slope={x:0,y:0};c.pin={x:390,y:30};c.green={x:210,y:330,rx:1000,ry:1000};if(lie==='sand')c.bunkers=[{x:210,y:330,rx:1000,ry:1000}];return c;}
function finish(b,c){const events=[];for(let i=0;i<3600&&b.moving;i++){const e=step(b,c);if(e)events.push(e);}assert.equal(b.moving,false,'ball must settle');return events;}
test('seed generates the same complete hole, and holes differ',()=>{assert.deepEqual(generateCourse('WEEKEND',2),generateCourse('WEEKEND',2));assert.notDeepEqual(generateCourse('WEEKEND',2),generateCourse('WEEKEND',3));});
test('500 generated holes have safe tees, greens and an open fairway centerline',()=>{for(let seed=0;seed<500;seed++){const c=generateCourse(String(seed),seed%9);assert.equal(terrain(c,c.tee),'tee');assert.equal(terrain(c,c.pin),'green');for(let i=1;i<c.points.length;i++){const a=c.points[i-1],b=c.points[i];for(let t=0;t<=1;t+=.025){const p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};assert.notEqual(terrain(c,p),'water');assert.ok(c.trees.every(tree=>dist(p,tree)>7));}}assert.ok(c.water.every(e=>pathDistance(e,c.points)>c.width+e.rx));}});
test('putts roll and decelerate without airborne motion',()=>{const c=flat(),b=makeBall({x:100,y:400});strike(b,c,'putter',0,.8);step(b,c);assert.equal(b.z,0);finish(b,c);assert.ok(b.x>160&&b.x<220);assert.equal(b.vx,0);});
test('sand slows a putt much more than green',()=>{const green=flat(),sand=flat('sand');const a=makeBall({x:100,y:400}),b=makeBall(a);strike(a,green,'putter',0,1);strike(b,sand,'putter',0,1);finish(a,green);finish(b,sand);assert.ok(a.x-100>(b.x-100)*5);});
test('wedges loft and settle; wind deflects flight',()=>{const c=flat(),windy=flat();windy.wind={x:8,y:0};const a=makeBall({x:210,y:560}),b=makeBall(a);strike(a,c,'wedge',-Math.PI/2,1);strike(b,windy,'wedge',-Math.PI/2,1);let maxZ=0;for(let i=0;i<200;i++){step(a,c);maxZ=Math.max(maxZ,a.z);}finish(a,c);finish(b,windy);assert.ok(maxZ>35);assert.ok(b.x>a.x+8);});
test('water returns to the shot position with one event',()=>{const c=flat();c.water=[{x:150,y:400,rx:22,ry:40}];const b=makeBall({x:100,y:400});strike(b,c,'putter',0,1);assert.deepEqual(finish(b,c),['water']);assert.equal(b.x,100);assert.equal(b.y,400);assert.equal(step(b,c),null);});
test('slow ball drops in cup; a very fast ball rolls over',()=>{const c=flat();c.pin={x:150,y:400};const b=makeBall({x:130,y:400});strike(b,c,'putter',0,.45);assert.ok(finish(b,c).includes('hole'));assert.equal(b.sunk,true);const fast=makeBall({x:130,y:400});strike(fast,c,'putter',0,1);finish(fast,c);assert.equal(fast.sunk,false);});
test('low shots collide with tree trunks',()=>{const c=flat();c.trees=[{x:150,y:400,r:16}];const b=makeBall({x:110,y:400});strike(b,c,'putter',0,1);finish(b,c);assert.ok(b.x<143);});
test('preview and real simulation agree across every club',()=>{for(const club of Object.keys(CLUBS)){const c=generateCourse('prediction',3),b=makeBall(c.tee);const forecast=preview(c,b,club,-Math.PI/2,.72);strike(b,c,club,-Math.PI/2,.72);finish(b,c);assert.ok(dist(b,forecast.end)<.001);}});
test('random shots stay finite and eventually stop',()=>{for(let i=0;i<120;i++){const c=generateCourse(String(i),i%9),b=makeBall(c.tee);strike(b,c,Object.keys(CLUBS)[i%4],i*2.399,.2+(i%9)/10);finish(b,c);assert.ok(Number.isFinite(b.x)&&Number.isFinite(b.y));assert.ok(b.x>=0&&b.x<=420&&b.y>=0&&b.y<=660);}});
